name: update-leaderboard

permissions:
  contents: write
  actions: read

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install matplotlib tabulate

    - name: Generate leaderboard
      run: python3 leaderboard.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add LEADERBOARD.md leaderboard.png
        git commit -m "Update leaderboard $(date '+%Y-%m-%d %H:%M:%S')" || echo "Нет изменений для коммита"
        git push
