name: update-leaderboard

permissions:
  contents: write
  actions: read

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install matplotlib tabulate

    - name: Generate leaderboard
      run: python3 leaderboard.py

    - name: Install Python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk  # Необходимо для matplotlib
        pip install --upgrade pip
        pip install matplotlib==3.7.1 tabulate==0.9.0
