name: update-leaderboard

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'  # Кэширование зависимостей

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-tk

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib==3.7.1 tabulate==0.9.0 --no-cache-dir

      - name: Generate leaderboard
        run: |
          python3 -c "import matplotlib; matplotlib.use('Agg')"  # Проверка установки
          python3 leaderboard.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add LEADERBOARD.md leaderboard.png
          git commit -m "Auto-update leaderboard $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
